-- Multi-format voucher assets: a voucher unit can now be backed by a QR, a plain
-- code, or a barcode, and the values can be supplied by the merchant instead of
-- generated by Wealth. Defaults keep every existing row on the original behaviour
-- (QR generated by Wealth), so this migration is backward compatible.

-- New enums
CREATE TYPE "VoucherFormat" AS ENUM ('QR', 'CODE', 'BARCODE');
CREATE TYPE "AssetSource" AS ENUM ('WEALTH_GENERATED', 'MERCHANT_UPLOADED');

-- Voucher: format + source + (optional) barcode symbology
ALTER TABLE "vouchers" ADD COLUMN "format" "VoucherFormat" NOT NULL DEFAULT 'QR';
ALTER TABLE "vouchers" ADD COLUMN "assetSource" "AssetSource" NOT NULL DEFAULT 'WEALTH_GENERATED';
ALTER TABLE "vouchers" ADD COLUMN "barcodeSymbology" TEXT;

-- QrCode: merchant-uploaded value (null for Wealth-generated rows). Unique per
-- voucher; Postgres treats NULLs as distinct so existing rows do not collide.
ALTER TABLE "qr_codes" ADD COLUMN "value" TEXT;
CREATE UNIQUE INDEX "qr_codes_voucherId_value_key" ON "qr_codes" ("voucherId", "value");
